version: '3.3'

services:
  myubuntu:
    image: myubuntu
    container_name: myubuntu
    command: /root/run/init.sh
    ports:
      - '10022:22'
      - '9092:9092'
    expose:
      - '10022'
      - '9092'