
spring.cloud.stream:
  kafka:
    binder:
      brokers: localhost
      defaultBrokerPort: 9092
  bindings:
    input:
      destination: test
      group: mygroup
      binder: kafka
    output:
      destination: tost
      group: mygorup
      binder: kafka
#debug: true

#spring:
#  cloud:
#    stream:
##      function.definition: aggregate;testSource;testSink
#      bindings:
##        aggregate-out-0:
##          destination: tost
#        aggregate-in-0:
#          destination: test
